name: Auto Build Some Kernels
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 6'
jobs:
  build:
    strategy:
      matrix:
        repos: [linux-bfq-dev, linux-ck, linux-clear, linux-gc, linux-libre, linux-libre-firmware, linux-lqx, linux-pds, thrash-protect, linux-pf-git, linux-rt, linux-rt-bfq-dev, linux-rt-lts, linux-uksm, linux-xanmod, linux-xanmod-anbox, linux-xanmod-cacule, linux-xanmod-edge, linux-xanmod-lts, linux-xanmod-rt, linux-next-git, linux-mainline, linux-lts419, linux-lts44, linux-lts49, linux-lts54]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: antman666/build-aur-action@master
        with:
          repo-name: ${{ matrix.repos }}
      - uses: ncipollo/release-action@v1.8.6
        with:
          allowUpdates: True
          tag: "x86_64"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
  pull_others_kernels:
    runs-on: ubuntu-latest
    steps:
      - name: Add Others Kernels
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install wget git -y
          git clone https://github.com/antman666/kernel-repo
          cd kernel-repo
          bash pull_kernels.sh
      - uses: ncipollo/release-action@v1.8.6
        with:
          allowUpdates: True
          tag: "x86_64"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
