name: Auto Build Some Kernels
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * 2,6'
jobs:
  build:
    strategy:
      matrix:
        repos: [linux-ck, linux-clear, linux-git, linux-libre, linux-lqx, linux-multimedia, linux-pds, thrash-protect, linux-pf-git, linux-shmilee, uksmd, linux-xanmod, linux-xanmod-anbox, linux-xanmod-edge, linux-xanmod-lts, linux-xanmod-rt, linux-xanmod-tt, linux-next-git, linux-mainline, linux-lts419, linux-lts49, linux-lts54, linux-lts510]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: antman666/build-aur-action@master
        with:
          repo-name: ${{ matrix.repos }}
      - uses: ncipollo/release-action@v1.11.1
        with:
          allowUpdates: True
          tag: "x86_64"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
