name: Auto Build Some Kernels
on: push
jobs:
  build_clear:
    runs-on: ubuntu-latest
    steps:
      - name: build_clear
        uses: antman666/build-aur-action@master
        with:
          repo-name: linux-clear
      - uses: ncipollo/release-action@v1.8.6
        with:
          allowUpdates: true
          tag: "linux-clear"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
  build_projectC:
    runs-on: ubuntu-latest
    steps:
      - name: build_projectC
        uses: antman666/build-aur-action@master
        with:
          repo-name: linux-gc
      - uses: ncipollo/release-action@v1.8.6
        with:
          allowUpdates: True
          tag: "linux-gc"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
  build_lqx: 
    runs-on: ubuntu-latest
    steps:
      - name: build_lqx  
        uses: antman666/build-aur-action@master
        with:
          repo-name: linux-lqx
      - uses: ncipollo/release-action@v1.8.6
        with:
          allowUpdates: True
          tag: "linux-lqx"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
