name: Auto Build Some Kernels
on: 
  schedule:
    - cron: 0 23 */3 * *
jobs:
  build:
    strategy:
      matrix:
        repos: [linux-bfq-dev, linux-ck, linux-clear, linux-clear-current, linux-clear-lts2020, linux-gc, linux-libre, linux-lqx, linux-pds, linux-pf, linux-pf-git, linux-rt, linux-rt-bfq-dev, linux-uksm, linux-xanmod, linux-xanmod-cacule, linux-xanmod-rt, linux-zen-g14, linux-next, linux-mainline]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: antman666/build-aur-action@master
        with:
          repo-name: ${{ matrix.repos }}
      - uses: ncipollo/release-action@v1.8.6
        with:
          allowUpdates: True
          tag: "linux_kernels"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
