name: Github Action Build PKGBUILD
on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 6'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-cjktty
        uses: actions/checkout@v2.3.4
      - id: makepkg
        uses: edlanglois/pkgbuild-action@v1.1.6
        with:
          pkgdir: "linux-cjktty"
          namcapDisable: 1
          makepkgArgs: "--skippgpcheck"
          aurDeps: 1
      - uses: ncipollo/release-action@v1.8.6
        with:
          allowUpdates: True
          tag: "x86_64"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
