name: Update kernel db
on: 
  push:
  workflow_dispatch:
  schedule: 
    - cron: '0 8 */6 * *'
jobs: 
  update_db:
    runs-on: ubuntu-latest
    steps: 
      - uses: antman666/update-db-for-repo@master
        with: 
          tag: x86_64
      - uses: ncipollo/release-action@v1.8.6
        with:
          allowUpdates: True
          tag: "x86_64"
          artifacts: "./kernels.*"
          token: ${{ secrets.GITHUB_TOKEN }}
