name: Update Kernels db
on:
  workflow_dispatch:

jobs:
  update_db:
    runs-on: ubuntu-latest
    steps: 
      - uses: antman666/update-db-for-repo@master
        with: 
          tag: x86_64
      - uses: ncipollo/release-action@main
        with:
          allowUpdates: True
          tag: "x86_64"
          artifacts: "./cosmic.*"
          token: ${{ secrets.GITHUB_TOKEN }}
