name: Update kernels.db
on: 
  workflow_dispatch:
  schedule: 
    - cron: '0 1 * * 0'
jobs: 
  pull_others_kernels:
    runs-on: ubuntu-latest
    steps:
      - name: Add Others Kernels
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install wget git -y
          git clone https://github.com/antman666/kernel-repo
          cd kernel-repo
          bash pull_kernels.sh
      - uses: ncipollo/release-action@v1.8.6
        with:
          allowUpdates: True
          tag: "x86_64"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
  update_db:
    needs: pull_others_kernels
    runs-on: ubuntu-latest
    steps: 
      - uses: antman666/update-db-for-repo@master
        with: 
          tag: x86_64
      - uses: ncipollo/release-action@v1.8.6
        with:
          allowUpdates: True
          tag: "x86_64"
          artifacts: "./kernels.*"
          token: ${{ secrets.GITHUB_TOKEN }}
